/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "acquisition.h"
#include "sihft.h"
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void Init(void) {
	ACQ_Init();
}

int main(void) {
	 SCB->CPACR |= (0xFU << 20);
	 __DSB();
	 __ISB();
	Init();
	Led_On();
	while(1) {
		SIHFT_StoreData();
		SIHFT_DataCheck();
		SIHFT_InstrCheck();
		SIHFT_Decide();
	}
}
